version: "3.8"

services:
  db:
    image: postgres:17
    container_name: agnos_db
    environment:
      POSTGRES_USER: agnos
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agnos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agnos_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agnos_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - agnos_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: agnos_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - agnos_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  agnos_network:
    driver: bridge